
language: java
jdk:
- openjdk8
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - bren@juanantonio.info
script:
- ./mvnw clean package
- docker build -t azure_function_image .
- docker run -p 80:80 --sysctl net.ipv6.conf.all.disable_ipv6=1 --name azure_function_image azure_function_image
- docker ps -a
- docker stop azure_function_image
- docker rm azure_function_image