language: java
jdk:
- openjdk8
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - bren@juanantonio.info
script:
- ./mvnw clean package
- source ./scripts/e2e_travis_tests.sh
